"""empty message

Revision ID: 47da9e08daff
Revises: 6ea436cdbf60
Create Date: 2021-05-15 11:53:29.704337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47da9e08daff'
down_revision = '6ea436cdbf60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_choices', sa.Column('choices_results', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll_choices', 'choices_results')
    # ### end Alembic commands ###
