"""empty message

Revision ID: 845692322d31
Revises: 
Create Date: 2021-04-13 21:29:27.974299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845692322d31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('by_who', sa.String(length=20), nullable=False),
    sa.Column('suggestion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestions')
    # ### end Alembic commands ###
